// AUTO-GENERATED by scripts/build_per_module_fixtures.py — do not edit by hand.
// Regenerate: scripts/.venv/bin/python scripts/build_per_module_fixtures.py

import type { Category, Course, ModuleEntry, ModuleListItem, ModuleStatus } from '../types'

import modulesListJson from './modules_list.json'

import mod_MAT1_01 from './modules/MAT1-01.json'
import mod_ARIN_AI1 from './modules/ARIN-AI1.json'
import mod_BARB_21 from './modules/BARB-21.json'
import mod_IPSS_15 from './modules/IPSS-15.json'
import mod_ALG_01 from './modules/ALG-01.json'
import mod_TGKI_WB1_1 from './modules/TGKI-WB1-1.json'
import mod_MATH_A2 from './modules/MATH-A2.json'
import mod_SECOS_B5_8 from './modules/SECOS-B5-8.json'
import mod_DBSYS1_14 from './modules/DBSYS1-14.json'

import courses_MAT1_01 from './courses/MAT1-01.json'
import courses_ARIN_AI1 from './courses/ARIN-AI1.json'
import courses_BARB_21 from './courses/BARB-21.json'
import courses_IPSS_15 from './courses/IPSS-15.json'
import courses_ALG_01 from './courses/ALG-01.json'
import courses_TGKI_WB1_1 from './courses/TGKI-WB1-1.json'
import courses_MATH_A2 from './courses/MATH-A2.json'
import courses_SECOS_B5_8 from './courses/SECOS-B5-8.json'
import courses_DBSYS1_14 from './courses/DBSYS1-14.json'

export const fixtureModulesList: ModuleListItem[] = modulesListJson as ModuleListItem[]

/**
 * Per-module raw rows (matches a `modules` row + parsed `details` JSONB).
 * The corresponding child courses live in `courses/<basename>.json`.
 */
const fixturePairs: ReadonlyArray<{ mod: unknown; courses: unknown }> = [
  { mod: mod_MAT1_01, courses: courses_MAT1_01 },
  { mod: mod_ARIN_AI1, courses: courses_ARIN_AI1 },
  { mod: mod_BARB_21, courses: courses_BARB_21 },
  { mod: mod_IPSS_15, courses: courses_IPSS_15 },
  { mod: mod_ALG_01, courses: courses_ALG_01 },
  { mod: mod_TGKI_WB1_1, courses: courses_TGKI_WB1_1 },
  { mod: mod_MATH_A2, courses: courses_MATH_A2 },
  { mod: mod_SECOS_B5_8, courses: courses_SECOS_B5_8 },
  { mod: mod_DBSYS1_14, courses: courses_DBSYS1_14 },
]

/**
 * Joined `ModuleEntry[]` ready to drop into the `modules` ref in `App.vue`
 * — the same shape the Supabase queries assemble at runtime. Defaults filled
 * in: `recommended_semester=null`, `categories=[]`, `module_status='offen'`.
 */
export const fixtureModuleEntries: ModuleEntry[] = fixturePairs.map(({ mod, courses }) => ({
  ...(mod as Omit<ModuleEntry, 'recommended_semester' | 'categories' | 'courses' | 'module_status'>),
  recommended_semester: null,
  categories: [] as Category[],
  courses: courses as Course[],
  module_status: 'offen' as ModuleStatus,
}))

/** Lookup by `code` (the human-readable kuerzel, e.g. 'MAT1/01'). */
export const fixtureModulesByCode: Record<string, ModuleEntry> = Object.fromEntries(
  fixtureModuleEntries.map((m) => [m.code, m]),
)
