"""Split the sample fixture into per-module JSON files for frontend imports.

Reads:
  scripts/data/fixture_sample_modules.json   (9 hand-picked modules)
  scripts/data/fixture_sample_courses.json   (their 44 child courses)

Writes (under frontend/dev/fixtures/):
  modules/<sanitized-code>.json     — one Module row each
  courses/<sanitized-code>.json     — Course[] for that module
  modules_list.json                 — ModuleListItem[] (mirrors view_modules_table)
  index.ts                          — typed re-exports + lookup maps
  README.md                         — what's here, how to regenerate

`code` slashes become dashes for filenames: "MAT1/01" → "MAT1-01.json".
Synthesised UUID-substitutes use a stable "fixture-…" prefix so re-runs
produce the same ids.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
IN_MODULES = HERE / "data" / "fixture_sample_modules.json"
IN_COURSES = HERE / "data" / "fixture_sample_courses.json"
OUT_DIR = REPO / "frontend" / "dev" / "fixtures"


def sanitize(code: str) -> str:
    """'MAT1/01' -> 'MAT1-01'.  Filenames + the basis for synthesised ids."""
    return code.replace("/", "-")


def safe_ident(code: str) -> str:
    """'MAT1/01' -> 'MAT1_01'. TS variable name fragment."""
    return re.sub(r"[^A-Za-z0-9]", "_", code)


def strip_private(d: dict) -> dict:
    """Drop keys starting with '_' (notes/provenance internal to the picker)."""
    return {k: v for k, v in d.items() if not k.startswith("_")}


def main() -> int:
    raw_modules = json.loads(IN_MODULES.read_text(encoding="utf-8"))
    raw_courses = json.loads(IN_COURSES.read_text(encoding="utf-8"))

    # Group courses by parent module code
    by_code: dict[str, list[dict]] = {}
    for c in raw_courses:
        by_code.setdefault(c["module_code"], []).append(c)

    modules_dir = OUT_DIR / "modules"
    courses_dir = OUT_DIR / "courses"
    modules_dir.mkdir(parents=True, exist_ok=True)
    courses_dir.mkdir(parents=True, exist_ok=True)

    list_rows: list[dict] = []
    written: list[tuple[str, str]] = []  # (code, sanitized) for index generation

    for raw in raw_modules:
        code = raw["code"]
        slug = sanitize(code)
        module_id = f"fixture-{slug}"

        # ---------------- Module file ----------------
        module = strip_private(raw)
        module = {
            "id": module_id,
            **module,
            "created_at": None,
            "updated_at": None,
        }
        (modules_dir / f"{slug}.json").write_text(
            json.dumps(module, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

        # ---------------- Courses file ----------------
        course_rows: list[dict] = []
        for i, c in enumerate(by_code.get(code, [])):
            c = strip_private(c)
            # Drop FK-proxy and picker-internal fields; the rest is the
            # public Course shape.
            DROP = {"module_code", "parent_mhid", "parent_mid"}
            course_rows.append({
                "id": f"{module_id}-c{i}",
                "module_id": module_id,
                **{k: v for k, v in c.items() if k not in DROP},
                "created_at": None,
                "updated_at": None,
            })
        (courses_dir / f"{slug}.json").write_text(
            json.dumps(course_rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

        # ---------------- ModuleListItem (view_modules_table row) ----------------
        list_rows.append({
            "id": module_id,
            "kuerzel": module["code"],
            "name": module["name"],
            "start_semester": module["start_semester"],
            "koordinator": module["coordinator"],
            "version": module["version"],
            "is_mandatory": module["is_mandatory"],
            "is_specialization": module["is_specialization"],
            "specialization_name": module["specialization_name"],
            "language": module["language"],
        })
        written.append((code, slug))

    (OUT_DIR / "modules_list.json").write_text(
        json.dumps(list_rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    # ---------------- index.ts ----------------
    # Static imports (Vite needs them static for bundling); the joined
    # `ModuleEntry[]` form is what `App.vue` would normally assemble at
    # runtime from Supabase queries.
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/build_per_module_fixtures.py — do not edit by hand.",
        "// Regenerate: scripts/.venv/bin/python scripts/build_per_module_fixtures.py",
        "",
        "import type { Category, Course, ModuleEntry, ModuleListItem, ModuleStatus } from '../types'",
        "",
        "import modulesListJson from './modules_list.json'",
        "",
    ]
    for code, slug in written:
        ident = safe_ident(slug)
        lines.append(f"import mod_{ident} from './modules/{slug}.json'")
    lines.append("")
    for code, slug in written:
        ident = safe_ident(slug)
        lines.append(f"import courses_{ident} from './courses/{slug}.json'")
    lines.append("")
    lines.append("export const fixtureModulesList: ModuleListItem[] = modulesListJson as ModuleListItem[]")
    lines.append("")
    lines.append("/**")
    lines.append(" * Per-module raw rows (matches a `modules` row + parsed `details` JSONB).")
    lines.append(" * The corresponding child courses live in `courses/<basename>.json`.")
    lines.append(" */")
    lines.append("const fixturePairs: ReadonlyArray<{ mod: unknown; courses: unknown }> = [")
    for code, slug in written:
        ident = safe_ident(slug)
        lines.append(f"  {{ mod: mod_{ident}, courses: courses_{ident} }},")
    lines.append("]")
    lines.append("")
    lines.append("/**")
    lines.append(" * Joined `ModuleEntry[]` ready to drop into the `modules` ref in `App.vue`")
    lines.append(" * — the same shape the Supabase queries assemble at runtime. Defaults filled")
    lines.append(" * in: `recommended_semester=null`, `categories=[]`, `module_status='offen'`.")
    lines.append(" */")
    lines.append("export const fixtureModuleEntries: ModuleEntry[] = fixturePairs.map(({ mod, courses }) => ({")
    lines.append("  ...(mod as Omit<ModuleEntry, 'recommended_semester' | 'categories' | 'courses' | 'module_status'>),")
    lines.append("  recommended_semester: null,")
    lines.append("  categories: [] as Category[],")
    lines.append("  courses: courses as Course[],")
    lines.append("  module_status: 'offen' as ModuleStatus,")
    lines.append("}))")
    lines.append("")
    lines.append("/** Lookup by `code` (the human-readable kuerzel, e.g. 'MAT1/01'). */")
    lines.append("export const fixtureModulesByCode: Record<string, ModuleEntry> = Object.fromEntries(")
    lines.append("  fixtureModuleEntries.map((m) => [m.code, m]),")
    lines.append(")")
    lines.append("")
    (OUT_DIR / "index.ts").write_text("\n".join(lines), encoding="utf-8")

    # ---------------- README ----------------
    readme = f"""# Module fixtures

Auto-generated example data for the `ModuleEntry` / `Course` / `ModuleListItem`
types defined in `../types.ts`. Used by frontend code that wants to render
real-shaped module data before the Supabase tables are populated.

## Layout

```
fixtures/
├── modules_list.json          # ModuleListItem[] (mirrors `view_modules_table`)
├── modules/                   # one module row per file (raw `modules.*` columns)
│   ├── MAT1-01.json
│   └── …
├── courses/                   # one Course[] per file (same basename as parent module)
│   ├── MAT1-01.json
│   └── …
└── index.ts                   # typed re-exports + the joined ModuleEntry[] form
```

Filename rule: parent module code with `/` → `-`. Synthesised `id`s use a
stable `fixture-<slug>` prefix so re-runs produce identical ids (safe to
hardcode in tests).

## Importing

```typescript
import {{
  fixtureModuleEntries,      // ModuleEntry[] — joined modules + courses + defaults
  fixtureModulesList,        // ModuleListItem[] — slim list-page payload
  fixtureModulesByCode,      // Record<code, ModuleEntry>
}} from './fixtures'
```

`fixtureModuleEntries` is what `App.vue` would normally assemble at runtime
from Supabase queries. Drop it straight into the `modules` ref to render
the UI without a database connection.

## What's covered

The {len(written)} hand-picked modules each exercise a different schema corner —
single-int / range / cohort start_semester, mixed-language variants, sonstiges
overrides, role-based coordinators, multivalued course types, etc. See
`scripts/build_fixture.py` for the picks and rationale.

## Regenerating

```
scripts/.venv/bin/python scripts/build_per_module_fixtures.py
```

The script is idempotent. To pull in different modules, edit `PICKS` in
`scripts/build_fixture.py`, re-run that script, then re-run this one.
"""
    (OUT_DIR / "README.md").write_text(readme, encoding="utf-8")

    print(f"wrote {OUT_DIR.resolve().relative_to(REPO)}/")
    print(f"  modules/        ({len(written)} files)")
    print(f"  courses/        ({len(written)} files)")
    print(f"  modules_list.json ({len(list_rows)} rows)")
    print(f"  index.ts")
    print(f"  README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
